### ISSUE TITLE
Does not scan all auctions

### ISSUE THREAD

**Issue by DimaSheiko** [alchem1ster/WotLK-Auctionator#1]
When doing a GetAllScan the addon only scans the first page of the auction.
For example, in this case it only scanned 55000 auctions.
![image](https://user-images.githubusercontent.com/67640628/145891204-097792ff-48ed-41fc-8590-074730cfb789.png)

But in reality there are 111276 auctions.
![image](https://user-images.githubusercontent.com/67640628/145891348-3d5f611e-1546-41cc-8edd-4e3ac0f69200.png)

**Comment by alchem1ster** [comment]
Thanks for the feedback, @DimaSheiko 
- Firstly, GetAllScan didn't just scan the first page of the auction because, as you pointed out, there are 111276 lots in the auction at the moment, and the addon was able to analyze 55000 of them, which is 49% (almost half). One page of the auction contains only 50 lots, as indicated by the inscription "`Objetos 1 : 50`";
- Secondly, unfortunately 55,000 lots is the limit per query set by TrinityCore. No player can load more than 55000 lots in a single request within 15 minutes. This "bug" have any auction addon (at least at the time of the WotLK patch). You can read more about here: [TrinityCore/TrinityCore@7d5d79a](https://github.com/TrinityCore/TrinityCore/commit/7d5d79aa015b21969a1f5ca75ca3efe8cb842f25)
